language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - python3 -m pip install --user numpy scipy
  - python3 setup.py build_external
  - python3 setup.py install
  - python3 example.py --IDnumber=0
  - python3 example.py --IDnumber=1
  - python3 example.py --IDnumber=2
  - python3 example.py --IDnumber=3
  - python3 example.py --IDnumber=4
  - python3 example.py --IDnumber=5
  - python3 example.py --IDnumber=6
  - python3 example.py --IDnumber=7
  - python3 example.py --IDnumber=8
