language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - python3 -m pip install --force-reinstall numpy scipy
  - python3 setup.py build_external
  - python3 setup.py install
  - python3 example.py --IDnumber=0
  - python3 example.py --IDnumber=1
  - python3 example.py --IDnumber=2
  - python3 example.py --IDnumber=3
  - python3 example.py --IDnumber=4
  - python3 example.py --IDnumber=5
  - python3 example.py --IDnumber=6
  - python3 example.py --IDnumber=7
  - python3 example.py --IDnumber=8
